# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(480, 640)
        Dialog.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Dialog.setStyleSheet(
""          
"background-color: rgb(67, 67, 67)"
"}\n"
"QPushButton{\n"
"    font: 48pt \"Microsoft Yi Baiti\";\n"
"    font-size: 20px;\n"
"    background-color: rgb(255, 120, 57);\n"
"    border: None;\n"
"}\n"
"QTextEdit{\n"
"    background-color: white\n"
"}\n"
"QLineEdit{\n"
"    border: None;\n"
"    background-color: white\n"
"}\n"
"")
      #  Dialog.setSizeGripEnabled(False)
      #  Dialog.setModal(False)
        self.GenerateButton = QtWidgets.QPushButton(Dialog)
        self.GenerateButton.setEnabled(True)
        self.GenerateButton.setGeometry(QtCore.QRect(0, 0, 160, 60))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yi Baiti")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.GenerateButton.setFont(font)
        self.GenerateButton.setStyleSheet("")
        self.GenerateButton.setCheckable(True)
        self.GenerateButton.setObjectName("GenerateButton")
        self.Cipher_button = QtWidgets.QPushButton(Dialog)
        self.Cipher_button.setGeometry(QtCore.QRect(160, 0, 160, 60))
        self.Cipher_button.setStyleSheet("")
        self.Cipher_button.setObjectName("Cipher_button")
        self.Decipher_Button = QtWidgets.QPushButton(Dialog)
        self.Decipher_Button.setGeometry(QtCore.QRect(320, 0, 160, 60))
        self.Decipher_Button.setStyleSheet("")
        self.Decipher_Button.setObjectName("Decipher_Button")
        self.Stacked_widget = QtWidgets.QStackedWidget(Dialog)
        self.Stacked_widget.setGeometry(QtCore.QRect(0, 60, 480, 540))
        self.Stacked_widget.setStyleSheet("QTextEdit::AlignCenter{}\n"
"QRadioButton{\n"
"    text-align: center;\n"
"    padding: 10px;\n"
"    font-size: 20px;\n"
"    border: 2px solid white;\n"
"    color: white;\n"
"}\n"
"QDialog {\n"
"    background-color: rgb(67, 67, 67)\n"
"}")
        self.Stacked_widget.setObjectName("Stacked_widget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.Generate_start = QtWidgets.QPushButton(self.page_1)
        self.Generate_start.setGeometry(QtCore.QRect(70, 360, 340, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yi Baiti")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Generate_start.setFont(font)
        self.Generate_start.setObjectName("Generate_start")
        self.radio_symbols_2 = QtWidgets.QRadioButton(self.page_1)
        self.radio_symbols_2.setGeometry(QtCore.QRect(70, 90, 340, 50))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.radio_symbols_2.setFont(font)
        self.radio_symbols_2.setObjectName("radio_symbols_2")
        self.radio_symbols_4 = QtWidgets.QRadioButton(self.page_1)
        self.radio_symbols_4.setGeometry(QtCore.QRect(70, 230, 340, 70))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.radio_symbols_4.setFont(font)
        self.radio_symbols_4.setObjectName("radio_symbols_4")
        self.radio_symbols_3 = QtWidgets.QRadioButton(self.page_1)
        self.radio_symbols_3.setGeometry(QtCore.QRect(70, 150, 340, 70))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.radio_symbols_3.setFont(font)
        self.radio_symbols_3.setObjectName("radio_symbols_3")
        self.radio_symbols_ = QtWidgets.QRadioButton(self.page_1)
        self.radio_symbols_.setGeometry(QtCore.QRect(70, 30, 340, 50))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.radio_symbols_.setFont(font)
        self.radio_symbols_.setAutoFillBackground(False)
        self.radio_symbols_.setChecked(True)
        self.radio_symbols_.setObjectName("radio_symbols_")
        self.Length_password = QtWidgets.QLineEdit(self.page_1)
        self.Length_password.setGeometry(QtCore.QRect(70, 310, 340, 40))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        self.Length_password.setFont(font)
        self.Length_password.setMaxLength(5)
        self.Length_password.setAlignment(QtCore.Qt.AlignCenter)
        self.Length_password.setObjectName("Length_password")
        self.Password_text = QtWidgets.QTextEdit(self.page_1)
        self.Password_text.setGeometry(QtCore.QRect(70, 420, 340, 90))
        self.Password_text.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Password_text.setAutoFillBackground(False)
        self.Password_text.setDocumentTitle("")
        self.Password_text.setReadOnly(True)
        self.Password_text.setObjectName("Password_text")
        self.Stacked_widget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.Cipher_start = QtWidgets.QPushButton(self.page_2)
        self.Cipher_start.setGeometry(QtCore.QRect(70, 200, 340, 50))
        self.Cipher_start.setObjectName("Cipher_start")
        self.Password_text_cipher_1 = QtWidgets.QTextEdit(self.page_2)
        self.Password_text_cipher_1.setGeometry(QtCore.QRect(70, 100, 340, 90))
        self.Password_text_cipher_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Password_text_cipher_1.setAutoFillBackground(False)
        self.Password_text_cipher_1.setDocumentTitle("")
        self.Password_text_cipher_1.setReadOnly(False)
        self.Password_text_cipher_1.setObjectName("Password_text_cipher_1")
        self.Password_text_cipher_3 = QtWidgets.QTextEdit(self.page_2)
        self.Password_text_cipher_3.setGeometry(QtCore.QRect(70, 360, 340, 90))
        self.Password_text_cipher_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Password_text_cipher_3.setAutoFillBackground(False)
        self.Password_text_cipher_3.setDocumentTitle("")
        self.Password_text_cipher_3.setReadOnly(True)
        self.Password_text_cipher_3.setObjectName("Password_text_cipher_3")
        self.Password_text_cipher_2 = QtWidgets.QTextEdit(self.page_2)
        self.Password_text_cipher_2.setGeometry(QtCore.QRect(70, 260, 340, 90))
        self.Password_text_cipher_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Password_text_cipher_2.setAutoFillBackground(False)
        self.Password_text_cipher_2.setDocumentTitle("")
        self.Password_text_cipher_2.setReadOnly(True)
        self.Password_text_cipher_2.setObjectName("Password_text_cipher_2")
        self.Stacked_widget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.Password_text_decipher_2 = QtWidgets.QTextEdit(self.page_3)
        self.Password_text_decipher_2.setGeometry(QtCore.QRect(70, 200, 340, 90))
        self.Password_text_decipher_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Password_text_decipher_2.setAutoFillBackground(False)
        self.Password_text_decipher_2.setDocumentTitle("")
        self.Password_text_decipher_2.setReadOnly(False)
        self.Password_text_decipher_2.setObjectName("Password_text_decipher_2")
        self.Decipher_start = QtWidgets.QPushButton(self.page_3)
        self.Decipher_start.setGeometry(QtCore.QRect(70, 300, 340, 50))
        self.Decipher_start.setObjectName("Decipher_start")
        self.Password_text_decipher_1 = QtWidgets.QTextEdit(self.page_3)
        self.Password_text_decipher_1.setGeometry(QtCore.QRect(70, 100, 340, 90))
        self.Password_text_decipher_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Password_text_decipher_1.setAutoFillBackground(False)
        self.Password_text_decipher_1.setDocumentTitle("")
        self.Password_text_decipher_1.setReadOnly(False)
        self.Password_text_decipher_1.setObjectName("Password_text_decipher_1")
        self.Password_text_decipher_3 = QtWidgets.QTextEdit(self.page_3)
        self.Password_text_decipher_3.setGeometry(QtCore.QRect(70, 360, 340, 90))
        self.Password_text_decipher_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Password_text_decipher_3.setAutoFillBackground(False)
        self.Password_text_decipher_3.setDocumentTitle("")
        self.Password_text_decipher_3.setReadOnly(True)
        self.Password_text_decipher_3.setObjectName("Password_text_decipher_3")
        self.Stacked_widget.addWidget(self.page_3)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(180, 610, 120, 15))
        self.label.setStyleSheet("color: white;\n"
"")
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        self.Stacked_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "PassTaCypher"))
        self.GenerateButton.setText(_translate("Dialog", "GENERATE"))
        self.Cipher_button.setText(_translate("Dialog", "CIPHER"))
        self.Decipher_Button.setText(_translate("Dialog", "DECIPHER"))
        self.Generate_start.setText(_translate("Dialog", "START"))
        self.radio_symbols_2.setText(_translate("Dialog", "Password will contain only digits"))
        self.radio_symbols_4.setText(_translate("Dialog", "Password will contain letters,\n"
"digits, punctuation"))
        self.radio_symbols_3.setText(_translate("Dialog", "Password will contain only letters \n"
"and digits"))
        self.radio_symbols_.setText(_translate("Dialog", "Password will contain only letters"))
        self.Length_password.setPlaceholderText(_translate("Dialog", "Length of password"))
        self.Password_text.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Password_text.setPlaceholderText(_translate("Dialog", "Your password"))
        self.Cipher_start.setText(_translate("Dialog", "START"))
        self.Password_text_cipher_1.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Password_text_cipher_1.setPlaceholderText(_translate("Dialog", "Your password"))
        self.Password_text_cipher_3.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Password_text_cipher_3.setPlaceholderText(_translate("Dialog", "Your password"))
        self.Password_text_cipher_2.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Password_text_cipher_2.setPlaceholderText(_translate("Dialog", "Your key"))
        self.Password_text_decipher_2.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Password_text_decipher_2.setPlaceholderText(_translate("Dialog", "Your key"))
        self.Decipher_start.setText(_translate("Dialog", "START"))
        self.Password_text_decipher_1.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Password_text_decipher_1.setPlaceholderText(_translate("Dialog", "Your password"))
        self.Password_text_decipher_3.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Password_text_decipher_3.setPlaceholderText(_translate("Dialog", "Your password"))
        self.label.setText(_translate("Dialog", "GitHub - Artemius10111"))

